<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \App\Entity\Formation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coutrevient' => [parent::class, 'coutrevient', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'diplomante' => [parent::class, 'diplomante', null],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null],
        "\0".parent::class."\0".'niveau' => [parent::class, 'niveau', null],
        "\0".parent::class."\0".'plans' => [parent::class, 'plans', null],
        "\0".parent::class."\0".'typeform' => [parent::class, 'typeform', null],
        'coutrevient' => [parent::class, 'coutrevient', null],
        'description' => [parent::class, 'description', null],
        'diplomante' => [parent::class, 'diplomante', null],
        'duree' => [parent::class, 'duree', null],
        'id' => [parent::class, 'id', null],
        'libelle' => [parent::class, 'libelle', null],
        'niveau' => [parent::class, 'niveau', null],
        'plans' => [parent::class, 'plans', null],
        'typeform' => [parent::class, 'typeform', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
