<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4wyiLV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4wyiLV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4wyiLV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4wyiLV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4wyiLV1\App_KernelDevDebugContainer([
    'container.build_hash' => '4wyiLV1',
    'container.build_id' => '75ff5cf5',
    'container.build_time' => 1745833185,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4wyiLV1');
